# Config file for automatic testing at travis-ci.org
language: python
language: python
# Workaround for being able to use Python 3.7 (2019-03)
sudo: required
dist: xenial

matrix:
    include:
    - python: "2.7"
      env: DEPS="numpy nose"
    # As of 2018-10, Travis has installation problems with the DEPS below, so Python 3.3 is not tested anymore:
    #- python: "3.3"
    #  env: DEPS="numpy nose"
    - python: "3.4"
      env: DEPS="numpy nose"
    - python: "3.5"
      env: DEPS="numpy nose"
    - python: "3.6"
      env: DEPS="numpy nose"
    - python: "3.7"
      env: DEPS="numpy nose"
    - python: "3.7"
      env: DEPS="numpy nose"

before_install:
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install $DEPS
    - pip install codecov

script:
    - python setup.py egg_info
    - python setup.py nosetests -sv --with-coverage
    # Generate documentation
    #- cd doc
    #- make html
    
after_success:
    - codecov
