# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4

matrix:

env:
    #- NUMPY=true
    # - NUMPY=false  #!!!!!! to be put back later
    # - NUMPY=false PYTHON=python3 PYSUF=3 # uses Python 3.2
    # - NUMPY=true PYTHON=python3 PYSUF=3 # uses Python 3.2

# !!!! wheel needed, below??

# command to install dependencies
before_install:
    # Install the pip that supports wheel
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install wheel --upgrade
    
    #- sudo apt-get install python-numpy cython libatlas-dev liblapack-dev gfortran
    - sudo apt-get update

install:    
    - pip install --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors --upgrade "numpy==1.8.0"

 # command to run tests
script:
    - python setup.py egg_info
    - python setup.py nosetests -sv
    # Generate documentation
    #- cd doc
    #- make html
 
